# Generated by Django 6.0.6 on 2026-06-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='comment',
            new_name='parent',
        ),
    ]
