# Generated by Django 6.0.6 on 2026-06-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_comment_replies_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='parent',
            new_name='comment',
        ),
    ]
